language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
  global:
    - RUN_TESTS=1

matrix:
  fast_finish: true

  include:
    - php: 5.4
      env: RUN_CS=1 RUN_TESTS=0

    - php: 5.4
      env: RUN_TESTS=0 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$RUN_CS' = '1' ]; then composer require squizlabs/php_codesniffer; fi"

  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$RUN_TESTS' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$RUN_CS' = '1' ]; then ./vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"

notifications:
  email: false
